services:
  db:
    image: postgis15-arm
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-mydatabase}'
      POSTGRES_USER: '${DB_USERNAME:-myusername}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
